# Generated by Django 4.2.16 on 2024-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
